language : ruby
os : linux

before_install :
    - sudo apt-get install ruby
    - gem install bundler
    - bundle install

before_script :
    - git clone https://github.com/Shylock-Hg/Shylock-Hg.github.io.git _site

script :
    - ./init.sh build

after_success :
    - git config user.name "Shylock-Hg"
    - git congig user.email "tcath2s@gmail.com"
    - cd _site
    - git add --all && git commit -m "Update - $(date)"
    - git push -f "https://${GITHUB_TOKEN}@${TARGET_REPO}"

