language : ruby
os : linux

before_install :
    - sudo apt-get install ruby
    - gem install bundler
    - bundle install

#before_script :
#    - git clone https://github.com/Shylock-Hg/Shylock-Hg.github.io.git _site

script :
    - ./init.sh build

#after_success :
#    - git config user.name "Shylock-Hg"
#    - git congig user.email "tcath2s@gmail.com"
#    - cd _site
#    - git add --all && git commit -m "Update - $(date)"
#    - git push -f "https://${GITHUB_TOKEN}@${TARGET_REPO}"

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
#    keep-history: true
    email: tcath2s@gmail.com
    name: 'Shylock Hg'
    on:
        branch: master
#    local_dir: _site
    repo: Shylock-Hg/Shylock-Hg.github.io
    target_branch: master
